name: pip-audit
description: pipx run pip-audit
inputs:
  requirements-file:
    description: Path to the requirements file
    required: false
    default: ./requirements.txt

  # pip-audit_cli_arguments: # TODO?

runs:
  using: composite
  steps:
    - name: cat ${{ inputs.requirements-file }}
      shell: bash
      run: cat ${{ inputs.requirements-file }}

    - name: pip-audit
      shell: bash
      run: pipx run -- pip-audit --requirement ${{ inputs.requirements-file }}
      continue-on-error: true
