name: pip-audit
description: pipx run pip-audit
inputs:
  pip-audit_cli_arguments:
    description: Additional arguments to pass to pip-audit
    required: false
    default: ""

  requirements-file:
    description: Path to the requirements file
    required: false
    default: ./requirements.txt

  continue-on-error:
    description: Whether to continue on error
    required: false
    default: "true"

runs:
  using: composite
  steps:
    # nosemgrep: yaml.github-actions.security.run-shell-injection.run-shell-injection # FIXME
    - run: cat ${{ inputs.requirements-file }}
      shell: bash
      name: cat ${{ inputs.requirements-file }}

    # TODO? use gh-action-pip-audit? SEE: https://github.com/pypa/gh-action-pip-audit
    # nosemgrep: yaml.github-actions.security.run-shell-injection.run-shell-injection # FIXME
    - run: pipx run -- pip-audit --requirement ${{ inputs.requirements-file }} ${{ inputs.pip-audit_cli_arguments }}
      name: pip-audit -r ${{ inputs.requirements-file }}
      shell: bash
      continue-on-error: ${{ inputs.continue-on-error == 'true' }}
