name: pipx install
description: pipx install
inputs:
  requirements-file:
    description: Path to the requirements file
    required: false
    default: ./requirements.pipx.txt

runs:
  using: composite
  steps:
    # nosemgrep: yaml.github-actions.security.run-shell-injection.run-shell-injection # FIXME
    - run: cat ${{ inputs.requirements-file }}
      shell: bash
      name: cat ${{ inputs.requirements-file }}

    # FIXME
    # nosemgrep: yaml.github-actions.security.run-shell-injection.run-shell-injection # FIXME
    - run: cat ${{ inputs.requirements-file }} | sed 's/.*/"&"/' | xargs -n 1 pipx install
      shell: bash
      name: pipx install

    - name: pipx list
      shell: bash
      run: pipx list
