name: Dependencies Review & Audit

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      # github-actions-common/.../checkout
      ssh-private-key:
        type: string
        description: SSH private key
        required: false

      #
      # NOTE: vvv github-actions-python/.../setup
      python-version-file:
        type: string
        description: Python version to install
        required: false
        default: "" # auto-detect

      python-version:
        type: string
        description: Python version to install
        required: false
        default: ""

      architecture:
        type: string
        description: Architecture to install python
        required: false
        default: x64
      # NOTE: ^^^ github-actions-python/.../setup

      #
      # NOTE: vvv github-actions-pip/.../install-upgrade
      pip_cli_options:
        type: string
        description: Options to pass to the pip command
        required: false
        default: "--verbose"

      upgrade-requirements-file:
        type: string
        description: Path to the requirements file
        required: false
        default: ./requirements.upgrade.txt
      # NOTE: ^^^ github-actions-pip/.../install-upgrade

      #
      # NOTE: vvv run_pip-audit
      pip-audit_cli_arguments:
        type: string
        description: Options to pass to the pip-audit command
        required: false
        default: ""

      audit-requirements-file:
        type: string
        description: Path to the requirements file
        required: false
        default: ./requirements.txt

      release-requirements-file:
        type: string
        description: Path to the requirements file
        required: false
        default: ""

      continue-on-error:
        type: boolean
        description: Whether to continue on error
        required: false
        default: false
      # NOTE: ^^^ run_pip-audit

permissions:
  contents: read

jobs:
  dependency-review:
    # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
    uses: percebus/github-actions-compliance/.github/workflows/dependency-review.yml@main
    with:
      ssh-private-key: ${{ inputs.ssh-private-key }}
    permissions:
      contents: read
      pull-requests: read

  # NOTE: is this job redundant?
  # does dependency-review-action accomplish the same, and more?
  pip-audit:
    # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
    uses: percebus/github-actions-pipx/.github/workflows/run_pip-audit.yml@main
    name: pipx
    with:
      # github-actions-common/.../checkout
      ssh-private-key: ${{ inputs.ssh-private-key }}

      # github-actions-python/.../setup
      python-version-file: ${{ inputs.python-version-file }}
      python-version: ${{ inputs.python-version }}
      architecture: ${{ inputs.architecture }}

      # github-actions-pip/.../install-upgrade
      pip_cli_options: ${{ inputs.pip_cli_options }}
      upgrade-requirements-file: ${{ inputs.upgrade-requirements-file }}

      # github-actions-pipx/.../run_pip-audit
      pip-audit_cli_arguments: ${{ inputs.pip-audit_cli_arguments }}
      audit-requirements-file: ${{ inputs.audit-requirements-file }}
      release-requirements-file: ${{ inputs.release-requirements-file }}
      continue-on-error: ${{ inputs.continue-on-error }}

  semgrep_ci:
    uses: percebus/github-actions-pipx/.github/workflows/run_semgrep_ci.yml@main
    name: pipx
    with:
      # github-actions-common/.../checkout
      ssh-private-key: ${{ inputs.ssh-private-key }}

      # github-actions-python/.../setup
      python-version-file: ${{ inputs.python-version-file }}
      python-version: ${{ inputs.python-version }}
      architecture: ${{ inputs.architecture }}

      # github-actions-pip/.../install-upgrade
      pip_cli_options: ${{ inputs.pip_cli_options }}
      upgrade-requirements-file: ${{ inputs.upgrade-requirements-file }}
