name: Pull Request

# "This run was triggered by the "push" event, which is unsupported.
#  Please ensure you are using the "pull_request" event for this workflow."
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  github-actions-pipx:
    uses: ./.github/workflows/dependency-review.yml
    name: github-actions-pipx
    permissions:
      contents: read
      pull-requests: read

  npm_audit:
    # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
    uses: percebus/github-actions-npm/.github/workflows/audit.yml@main
    name: npm
