name: Test workflows/run_pip-audit_path

on:
  push:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  python__matrix:
    # if: false # FIXME not working
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - 3.10
          - 3.11
          - 3.12
          # - 3.13  # Already tested from .python-version

    name: python @ ${{ matrix.python-version }}
    uses: ./.github/workflows/run_pip-audit_path.yml
    with:
      python-version: ${{ matrix.python-version }}

  pyproject_toml__matrix:
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        example:
          - algorithmic-excercises

    name: "examples/${{ matrix.example }}"
    uses: ./.github/workflows/run_pip-audit_path.yml
    with:
      project_path: ./assets/examples/${{ matrix.example }}
