name: Test workflows/run_pip-audit

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  default:
    uses: ./.github/workflows/run_pip-audit.yml

  algorithmic-exercises_requirements:
    needs: default
    if: false # FIXME takes forever
    name: "algorithmic-exercises: requirements"
    uses: ./.github/workflows/run_pip-audit.yml
    with:
      audit-requirements-file: ./assets/examples/algorithmic-exercises_pip/requirements.txt
      release-requirements-file: ./assets/examples/algorithmic-exercises_pip/requirements.release.txt

  algorithmic-exercises_requirements_require-hashes:
    needs: default
    name: "algorithmic-exercises: requirements"
    uses: ./.github/workflows/run_pip-audit.yml
    with:
      pip-audit_cli_arguments: "--require-hashes --disable-pip"
      audit-requirements-file: ./assets/examples/algorithmic-exercises_pip/requirements.poetry.dev.txt
      release-requirements-file: ./assets/examples/algorithmic-exercises_pip/requirements.poetry.main.txt

  #
  python__matrix:
    needs: default

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - "3.13"
          - "3.14"

    name: python @ ${{ matrix.python-version }}
    uses: ./.github/workflows/run_pip-audit.yml
    with:
      python-version: ${{ matrix.python-version }}

  #
  requirements-file__matrix:
    needs: default

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        example:
          - pypyr/requirements.pipx.txt
          - poetry/requirements.pipx.txt
          - uv/requirements.pipx.txt
          - misc1/requirements.pipx.txt

    name: "-r ${{ matrix.example }}"
    uses: ./.github/workflows/run_pip-audit.yml
    with:
      audit-requirements-file: ./assets/examples/${{ matrix.example }}
