name: Test workflows/run_pip-audit_path

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  default:
    uses: ./.github/workflows/run_pip-audit_path.yml
    with:
      project_path: ./assets/examples/uv-empty-pyproject

  #
  python__matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - "3.13"
          - "3.14"

    name: python @ ${{ matrix.python-version }}
    uses: ./.github/workflows/run_pip-audit_path.yml
    with:
      project_path: ./assets/examples/uv-empty-pyproject
      python-version: ${{ matrix.python-version }}

  #
  poetry__matrix:
    needs: default
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        example:
          - algorithmic-exercises_poetry

    name: ${{ matrix.example }}
    uses: ./.github/workflows/run_pip-audit_path.yml
    with:
      project_path: ./assets/examples/${{ matrix.example }}
      pip-audit_cli_arguments: "--project poetry --locked"
