name: Test actions/run_pip-audit

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

      - uses: ./.github/actions/run_pip-audit

  #
  python__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        python-version:
          - "3.13"
          - "3.14"

    name: python @ ${{ matrix.python-version }}
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main
        with:
          python-version: ${{ matrix.python-version }}

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

      - uses: ./.github/actions/run_pip-audit

  #
  requirements-file__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        example:
          - pypyr/requirements.pipx.txt
          - poetry/requirements.pipx.txt
          - uv/requirements.pipx.txt
          - misc1/requirements.pipx.txt

    name: "-r ${{ matrix.example }}"
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

      - uses: ./.github/actions/run_pip-audit
        with:
          requirements-file: ./assets/examples/${{ matrix.example }}

  #
  # FIXME takes forever
  # algorithmic-exercises__matrix:
  #   needs: default
  #   runs-on: ubuntu-latest

  #   strategy:
  #     fail-fast: false
  #     max-parallel: 6
  #     matrix:
  #       example:
  #         - requirements.frozen.txt

  #   name: "-r ${{ matrix.example }}"
  #   steps:
  #     # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
  #     - uses: percebus/github-actions-common/.github/actions/checkout@main

  #     # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
  #     - uses: percebus/github-actions-python/.github/actions/setup@main

  #     # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
  #     - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

  #     - uses: ./.github/actions/run_pip-audit
  #       with:
  #         requirements-file: ./assets/examples/algorithmic-exercises_pip/${{ matrix.example }}

#
  algorithmic-exercises_require-hashes__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        example:
          - requirements.txt
          - requirements.release.txt

    name: "-r algorithmic-exercises/${{ matrix.example }}"
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

      - uses: ./.github/actions/run_pip-audit
        with:
          requirements-file: ./assets/examples/algorithmic-exercises_pip/${{ matrix.example }}
          pip-audit_cli_arguments: "--require-hashes"

  #
  algorithmic-exercises_require-hashes_disable-pip__matrix:
    needs: default
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        example:
          - requirements.poetry.main.txt
          - requirements.poetry.cli.txt
          - requirements.poetry.dev.txt

    name: "-r algorithmic-exercises/${{ matrix.example }}"
    steps:
      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-python/.github/actions/setup@main

      # nosemgrep: yaml.github-actions.security.github-actions-mutable-action-tag.github-actions-mutable-action-tag
      - uses: percebus/github-actions-pip/.github/actions/install-upgrade@main

      - uses: ./.github/actions/run_pip-audit
        with:
          requirements-file: ./assets/examples/algorithmic-exercises_pip/${{ matrix.example }}
          pip-audit_cli_arguments: "--require-hashes --disable-pip"
